import { Product } from "./type";


export const products: Product[]=[
  {
    id:1,
    title:"Green women kurti",
    image:["/pictures/green.jpg","/pictures/kurti2.webp"],
    slug:"Green-Women-Shirt-Piece",
    price: 2000,
    discount:20,
    category:"stitched",
    description:"Best quality fabrics for women wearing,it gives fascinate looks to an ordinay person,it grooms your personality.",
    size:["S","M","L","XL"],
    color:["#347928", "#6EC207", "#BEDC74"],
    Quantity:1,
  },
  
  {
    id:2,
    title:"Green women kurti",
    image:["/pictures/kurti3.jpg"],
    slug:"Women-Printed-Shirt",
    price: 2000,
    discount:20,
    category:"stitched",
    description:"Best quality fabrics for women wearing,it gives fascinate looks to an ordinay person,it grooms your personality.",
    size:["S","M","L","XL"],
    color:["#347928", "#6EC207", "#BEDC74"],
    Quantity:1,
  },
  {
    id:3,
    title:"Red women suit",
    image:["/pictures/suit3.jpg"],
    slug:"Red-Three-Piece",
    price: 6000,
    discount:30,
    category:"unstitched",
    description:"Best quality fabrics for women wearing,it gives fascinate looks to an ordinay person,it grooms your personality.",
    size:["S","M","L","XL"],
    color:["#B8001F", "#C7253E", "#821131"],
    Quantity:1,
  },
  {
    id:4,
    title:"Red women suit",
    image:["/pictures/suit7.jpg"],
    slug:"Unstitched-Red-Printed-Suit",
    price: 6000,
    discount:30,
    category:"unstitched",
    description:"Best quality fabrics for women wearing,it gives fascinate looks to an ordinay person,it grooms your personality.",
    size:["S","M","L","XL"],
    color:["#B8001F", "#C7253E", "#821131"],
    Quantity:1,
  },
  {
    id:5,
    title:"Blue women kurti",
    image:['/pictures/kurti4.jpg'],
    slug:"Blue-shirt-piece",
    price: 2000,
    discount:20,
    category:"stitched",
    description:"Best quality fabrics for women wearing,it gives fascinate looks to an ordinay person,it grooms your personality.",
    size:["S","M","L","XL"],
    color:["#243A73", "#0B2F9F", "#161D6F"],
    Quantity:1,
  },
  {
    id:6,
    title:"Blue women kurti",
    image:["/pictures/kurti5.jpg"],
    slug:"Blue-Printed-shirt-piece",
    price: 2000,
    discount:20,
    category:"stitched",
    description:"Best quality fabrics for women wearing,it gives fascinate looks to an ordinay person,it grooms your personality.",
    size:["S","M","L","XL"],
    color:["#243A73", "#0B2F9F", "#161D6F"],
    Quantity:1,
  },
  {
    id:7,
    title:"Black women suit",
    image:['/pictures/black1.webp'],
    slug:"Black-three-piece",
    price: 6000,
    discount:30,
    category:"unstitched",
    description:"Best quality fabrics for women wearing,it gives fascinate looks to an ordinay person,it grooms your personality.",
    size:["S","M","L","XL"],
    color:["#181C14", "#343131", "#4A4947"],
    Quantity:1,
  },
  {
    id:8,
    title:"Black women suit",
    image:["/pictures/suit6.jpg"],
    slug:"Black-Fancy-Net-suit",
    price: 6000,
    discount:30,
    category:"unstitched",
    description:"Best quality fabrics for women wearing,it gives fascinate looks to an ordinay person,it grooms your personality.",
    size:["S","M","L","XL"],
    color:["#181C14", "#343131", "#4A4947"],
    Quantity:1,
  },
  {
    id:9,
    title:"Gucci Brown Purse",
    image:["/pictures/purse2.webp"],
    slug:"Gucci-Brown-Purse",
    price: 3000,
    discount:25,
    category:"accessories",
    description:"Best quality hand carry,it gives fascinate looks,it grooms your personality.",
    size:["M","L"],
    color:["#654520", "#825B32", "#C96868"],
    Quantity:1 ,
  },
  {
    id:10,
    title:"Gucci Pink Purse",
    image:['/pictures/purse1.webp'],
    slug:"Gucci-Pink-Purse",
    price: 3000,
    discount:25,
    category:"accessories",
    description:"Best quality hand carry,it gives fascinate looks,it grooms your personality.",
    size:["M","L"],
    color:["#654520", "#825B32", "#C96868"],
    Quantity:1 ,
  },
  {
    id:11,
    title:"Pink Heels",
    image:['/pictures/pinkheel.jpg'],
    slug:"Pink-Sandals-for-women",
    price: 5000,
    discount:25,
    category:"shoes",
    description:"Best quality foot wear for women,it gives fascinate looks,it grooms your personality.",
    size:["6","7","8","9"],
    color:["#EE66A6", "#E7CCCC", "#FF4E88"],
    Quantity:1,
  },
  {
    id:12,
    title:"Pink Heels",
    image:["/pictures/shoe3.png"],
    slug:"Pink-Pumps-for-women",
    price: 5000,
    discount:30,
    category:"shoes",
    description:"Best quality foot wear for women,it gives fascinate looks,it grooms your personality.",
    size:["6","7","8","9"],
    color:["#EE66A6", "#E7CCCC", "#FF4E88"],
    Quantity:1,
  },
  {
    id:13,
    title:"White Woman Suit",
    image:['/pictures/suit2.webp'],
    slug:"White-three-piece",
    price: 6000,
    discount:30,
    category:"unstitched",
    description:"Best quality fabrics for women wearing,it gives fascinate looks to an ordinay person,it grooms your personality.",
    size:["S","M","L","XL"],
    color:["#FCFAEE", "#FFFBE6", "#F5F7F8"],
    Quantity:1,
  },
  {
    id:14,
    title:"White Woman Suit",
    image:["/pictures/suit1.jpg"],
    slug:"White-Fancy-three-piece",
    price: 6000,
    discount:20,
    category:"unstitched",
    description:"Best quality fabrics for women wearing,it gives fascinate looks to an ordinay person,it grooms your personality.",
    size:["S","M","L","XL"],
    color:["#FCFAEE", "#FFFBE6", "#F5F7F8"],
    Quantity:1,
  },
  {
    id:15,
    title:"Red Ladies Overcoat",
    image:['/pictures/overcoat3.jpg'],
    slug:"Red-Ladies-Overcoat",
    price: 6000,
    discount:20,
    category:"stitched",
    description:"Best quality fabrics for women wearing,it gives fascinate looks to an ordinay person,it grooms your personality.",
    size:["S","M","L","XL"],
    color:["#B8001F", "#C7253E", "#821131"],
    Quantity:1,
  },
  {
    id:16,
    title:"Red Ladies Overcoat",
    image:["/pictures/overcoat2.jpg"],
    slug:"Printed-Overcoat",
    price: 6000,
    discount:25,
    category:"stitched",
    description:"Best quality fabrics for women wearing,it gives fascinate looks to an ordinay person,it grooms your personality.",
    size:["S","M","L","XL"],
    color:["#B8001F", "#C7253E", "#821131"],
    Quantity:1,
  },
  {
    id:17,
    title:"Green women kurti",
    image:["/pictures/kurti2.webp"],
    slug:"Green-Women-Printed-Shirt-Piece",
    price: 2000,
    discount:20,
    category:"stitched",
    description:"Best quality fabrics for women wearing,it gives fascinate looks to an ordinay person,it grooms your personality.",
    size:["S","M","L","XL"],
    color:["#347928", "#6EC207", "#BEDC74"],
    Quantity:1,
  },
  {
    id:18,
    title:"Stylish Glasses",
    image:['/pictures/glasses2.jpg'],
    slug:"blue-glasses",
    price: 3000,
    discount:25,
    category:"accessories",
    description:"Best quality glasses,it gives fascinate looks,it grooms your personality.",
    size:["S","M"],
    color:["#1F509A", "#D4EBF8"],
    Quantity:1 ,
  },
  {
    id:19,
    title:"Stylish Watch",
    image:['/pictures/menwatch.jpg'],
    slug:"rado-watch",
    price: 4000,
    discount:25,
    category:"accessories",
    description:"Best quality watch,it gives fascinate looks,it grooms your personality.",
    size:["S","M"],
    color:["#E5E3D4", "#EEDF7A"],
    Quantity:1 ,
  },
  {
    id:20,
    title:"Stylish Watch",
    image:['/pictures/watch1.jpg'],
    slug:"rado-watch-pair",
    price: 4000,
    discount:25,
    category:"accessories",
    description:"Best quality watch,it gives fascinate looks,it grooms your personality.",
    size:["S","M"],
    color:["#E5E3D4", "#EEDF7A"],
    Quantity:1 ,
  },
  {
    id:21,
    title:"Stylish hat",
    image:['/pictures/cap.jpg'],
    slug:"red-man-hat",
    price: 1000,
    discount:25,
    category:"accessories",
    description:"Best quality hat,it gives fascinate looks,it grooms your personality.",
    size:["S","M"],
    color:["#FF2929", "#FCF596"],
    Quantity:1 ,
  },
  {
    id:21,
    title:"Stylish hat",
    image:['/pictures/hat.webp'],
    slug:"font-woman-hat",
    price: 1000,
    discount:25,
    category:"accessories",
    description:"Best quality hat,it gives fascinate looks,it grooms your personality.",
    size:["S","M"],
    color:["#FF2929", "#FCF596"],
    Quantity:1 ,
  },
  {
    id:22,
    title:"Flats",
    image:["/pictures/shoe2.jpg"],
    slug:"flats-for-women",
    price: 3000,
    discount:30,
    category:"shoes",
    description:"Best quality foot wear for women,it gives fascinate looks,it grooms your personality.",
    size:["6","7","8","9"],
    color:["#FF2929", "#FCF596"],
    Quantity:1,
  },
  {
    id:22,
    title:"Step Sandals",
    image:["/pictures/brown1.jpg"],
    slug:"stepsandals-for-women",
    price: 3000,
    discount:30,
    category:"shoes",
    description:"Best quality foot wear for women,it gives fascinate looks,it grooms your personality.",
    size:["6","7","8","9"],
    color:["#3D0301", "#1A1A1D"],
    Quantity:1,
  },
  {
    id:22,
    title:"Step Sandals Black",
    image:["/pictures/E4.jpeg"],
    slug:"stepsandals1-for-women",
    price: 3000,
    discount:30,
    category:"shoes",
    description:"Best quality foot wear for women,it gives fascinate looks,it grooms your personality.",
    size:["6","7","8","9"],
    color:["#3D0301", "#1A1A1D"],
    Quantity:1,
  },
  {
    id:22,
    title:"Flats Golden",
    image:["/pictures/shoe6.jpg"],
    slug:"flats-for-women",
    price: 3000,
    discount:30,
    category:"shoes",
    description:"Best quality foot wear for women,it gives fascinate looks,it grooms your personality.",
    size:["6","7","8","9"],
    color:["#FF2929", "#FCF596"],
    Quantity:1,
  },
  {
    id:23,
    title:"Smart Joggers",
    image:["/pictures/jogger.jpg"],
    slug:"joggers-for-women",
    price: 3000,
    discount:30,
    category:"shoes",
    description:"Best quality foot wear for women,it gives fascinate looks,it grooms your personality.",
    size:["6","7","8","9"],
    color:["#0A3981", "#4335A7"],
    Quantity:1,
  },
  {
    id:24,
    title:"Pink Joggers",
    image:["/pictures/jogger1.jpg"],
    slug:"joggers-for-women",
    price: 3000,
    discount:30,
    category:"shoes",
    description:"Best quality foot wear for women,it gives fascinate looks,it grooms your personality.",
    size:["6","7","8","9"],
    color:["#F0C1E1", "#D76C82"],
    Quantity:1,
  },
  {
    id:25,
    title:"Gucci Golden Purse",
    image:["/pictures/purse5.jpg"],
    slug:"Gucci-Golden-Purse",
    price: 3000,
    discount:25,
    category:"accessories",
    description:"Best quality hand carry,it gives fascinate looks,it grooms your personality.",
    size:["M","L"],
    color:["#FF2929", "#FCF596"],
    Quantity:1 ,
  },
  {
    id:26,
    title:"Smart Blue Joggers",
    image:["/pictures/jog2.jpg"],
    slug:"jogBlue-for-women",
    price: 3000,
    discount:30,
    category:"shoes",
    description:"Best quality foot wear for women,it gives fascinate looks,it grooms your personality.",
    size:["6","7","8","9"],
    color:["7BD3EA", "#80C4E9"],
    Quantity:1,
  },
  {
    id:27,
    title:"Black Stylish Glasses",
    image:['/pictures/glass1.jpg'],
    slug:"black-glasses",
    price: 3000,
    discount:25,
    category:"accessories",
    description:"Best quality glasses,it gives fascinate looks,it grooms your personality.",
    size:["S","M"],
    color:["#1A1A1D", "#3D5300"],
    Quantity:1 ,
  },
]